chhs-apqd-elasticsearch:
  container_name: chhs-apqd-elasticsearch
  restart: unless-stopped
  image: docker-registry-sdg.engagepoint.us:5000/chhs-apqd-elasticsearch
  # volumes:
  #   - ~/volumes/jhipster/chhs-apqd/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"

chhs-apqd-postgresql:
  container_name: chhs-apqd-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/chhs-apqd/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=chhs-apqd
    - POSTGRES_PASSWORD=
    - TZ=America/New_York
  ports:
    - "5432:5432"

chhs-apqd-neo4j:
    container_name: chhs-apqd-neo4j
    restart: unless-stopped
    image: neo4j:2.3.3
    ports:
    - "7474:7474"
    environment:
    - TZ=America/New_York
    - NEO4J_AUTH=neo4j/qwe123
    ulimits:
     nofile: 40000

chhs-apqd:
  container_name: chhs-apqd
  restart: unless-stopped
  image: docker-registry-sdg.engagepoint.us:5000/chhs-apqd
  environment:
    - COOKIE=SRV insert indirect nocache
    - spring_mail_host=172.24.232.25
    - TZ=America/New_York
#   - logback_graylogHost=LOGBACK_GRAYLOGHOST
  ports:
    - "8080:8080"
  links:
    - "chhs-apqd-postgresql:POSTGRESQL"
    - "chhs-apqd-elasticsearch:ELASTIC"
    - "chhs-apqd-neo4j:NEO4J"
