#
#
# to start chhs-apqd use:
#  docker-compose -f ha-chhs-apqd.yml up -d
#
# for scaling use
#  docker-compose -f ha-chhs-apqd.yml scale chhs-apqd=3
#
#

chhs-apqd-ha-elasticsearch:
  image: docker-registry-sdg.engagepoint.us:5000/chhs-apqd-elasticsearch
  restart: unless-stopped
  ports:
    - "9200"
    - "9300"

chhs-apqd-ha-postgresql:
  container_name: chhs-apqd-ha-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=chhs-apqd
    - POSTGRES_PASSWORD=
  ports:
    - "25432:5432"

chhs-apqd-ha:
  image: docker-registry-sdg.engagepoint.us:5000/chhs-apqd
  restart: unless-stopped
  environment:
    - COOKIE=SRV insert indirect nocache
    - spring_mail_host=172.24.232.25
    - TZ=America/New_York
#   - logback_graylogHost=LOGBACK_GRAYLOGHOST
  ports:
    - "8080"
  links:
    - "chhs-apqd-ha-postgresql:POSTGRESQL"
    - "chhs-apqd-ha-elasticsearch:ELASTIC"

chhs-apqd-ha-lb:
  container_name: chhs-apqd-haproxy
  restart: unless-stopped
  image: tutum/haproxy
  links:
   - "chhs-apqd-ha"
  ports:
   - "24080:80"
   - "24043:443"
  environment:
   - BACKEND_PORT=8080
   - BALANCE=roundrobin
