#
# to start chhs-apqd use:
#  docker-compose -f ha-chhs-apqd.yml up -d
#
# for scaling use
#  docker-compose -f ha-chhs-apqd.yml scale chhs-apqd=3
#
#

chhs-apqd-elasticsearch:
  image: docker-registry-sdg.engagepoint.us:5000/chhs-apqd-elasticsearch
  restart: unless-stopped
  ports:
    - "9200"
    - "9300"

chhs-apqd-postgresql:
  container_name: chhs-apqd-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=chhs-apqd
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"

chhs-apqd-neo4j:
    container_name: chhs-apqd-neo4j
    restart: unless-stopped
    image: neo4j:2.3.3
    ports:
    - "7474:7474"
    environment:
    - NEO4J_AUTH=neo4j/qwe123
    ulimits:
     nofile: 40000

chhs-apqd:
  image: docker-registry-sdg.engagepoint.us:5000/chhs-apqd
  restart: unless-stopped
  environment:
    - COOKIE=SRV insert indirect nocache
    - spring_mail_host=172.24.232.25
    - TZ=America/New_York
#   - logback_graylogHost=LOGBACK_GRAYLOGHOST
  ports:
    - "8080"
  links:
    - "chhs-apqd-postgresql:POSTGRESQL"
    - "chhs-apqd-elasticsearch:ELASTIC"
    - "chhs-apqd-neo4j:NEO4J"

chhs-apqd-lb:
  container_name: chhs-apqd-haproxy
  restart: unless-stopped
  image: tutum/haproxy
  links:
   - "chhs-apqd"
  ports:
   - "4080:80"
   - "4043:443"
  environment:
   - BACKEND_PORT=8080
   - BALANCE=roundrobin
