intake-elasticsearch:
  container_name: intake-elasticsearch
  restart: unless-stopped
  image: docker-registry-sdg.engagepoint.us:5000/intake-elasticsearch
  # volumes:
  #   - ~/volumes/jhipster/intake/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"

intake-postgresql:
  container_name: intake-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/intake/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=intake
    - POSTGRES_PASSWORD=
    - TZ=America/New_York
  ports:
    - "5432:5432"

intake-neo4j:
    container_name: intake-neo4j
    restart: unless-stopped
    image: neo4j:2.3.3
    ports:
    - "7474:7474"
    environment:
    - TZ=America/New_York
    - NEO4J_AUTH=neo4j/qwe123
    ulimits:
     nofile: 40000

intake:
  container_name: intake
  restart: unless-stopped
  image: docker-registry-sdg.engagepoint.us:5000/intake
  environment:
    - COOKIE=SRV insert indirect nocache
    - spring_mail_host=172.24.232.25
    - TZ=America/New_York
#   - logback_graylogHost=LOGBACK_GRAYLOGHOST
  ports:
    - "8080:8080"
  links:
    - "intake-postgresql:POSTGRESQL"
    - "intake-elasticsearch:ELASTIC"
    - "intake-neo4j:NEO4J"
