intake-elasticsearch:
  container_name: intake-elasticsearch
  restart: unless-stopped
  image: docker-registry-sdg.engagepoint.us:5000/intake-elasticsearch
  # volumes:
  #   - ~/volumes/jhipster/intake/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"

intake-postgresql:
  container_name: intake-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/intake/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=intake
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"

intake-neo4j:
    container_name: intake-neo4j
    restart: unless-stopped
    image: neo4j:2.3.3
    ports:
    - "7474:7474"
    environment:
    - NEO4J_AUTH=neo4j/qwe123
    ulimits:
     nofile: 40000
